# Metadata
title: Matthew J. Moran's Resume
tagline: Professional resume template and resources
description: A LaTeX-based resume template with resources and best practices for creating an effective resume.
author:
  name: Matthew J. Moran
  url: https://matthewjmoran.com/
social:
  name: Matthew J. Moran
  links:
    - https://github.com/mattjmoran
    - https://www.linkedin.com/in/matt-j-moran/
lang: en
locale: en_US
# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
