name: Build and Release
on:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - ".github/workflows/build.yaml"
permissions:
  contents: write
concurrency:
  group: "build"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        run: ./build.sh resume.tex
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: resume.pdf
